name: CI

on:
  workflow_dispatch:
    inputs:
      message:
        description: 'Message'     
        required: false
        default: 'none'

  push:
    branches:
      -master

  pull_request:
    branches:
      -master
  
jobs:
  ci_plt:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install build-essential \
        dia \
        libsfml-dev libxml2-dev libmicrohttpd-dev libboost-all-dev \
        python3 python3-pip \
        lcov gcovr \
        /

    - name: Build
      shell: bash
      run: |
        make all

    - name: Test
      working-directory: ${{runner.workspace}}/build/test
      shell: bash
      env:
        CTEST_OUTPUT_ON_FAILURE: 1
        BOOST_TEST_REPORT_LEVEL: detailed
      run: |
        ctest -VV --timeout 300
